<?php

use Illuminate\Database\Seeder;
use App\Question;

class QuestionTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        // TODO: IDs and parent_ids

        Question::create([
            'id' => 101,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '1',
            'order' => 1,
            'parent_id' => null,
            'text' => 'ID / TUB Project Number',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 1,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 102,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '2',
            'order' => 2,
            'parent_id' => null,
            'text' => 'Project Title',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: Auto-Import from IVMC database',
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 103,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '3',
            'order' => 3,
            'parent_id' => null,
            'text' => 'Project Description / Abstract (german)',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: Auto-Import from IVMC database',
            'reference' => null,
            'guidance' => 'Briefly summarize the type of study (or studies) to help others understand the purposes for which the data are being collected or created Project Description.',
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 104,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '4',
            'order' => 4,
            'parent_id' => null,
            'text' => 'Project Description / Abstract (english)',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: Auto-Import from IVMC database',
            'reference' => null,
            'guidance' => 'Briefly summarize the type of study (or studies) to help others understand the purposes for which the data are being collected or created Project Description.',
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 105,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '5',
            'order' => 5,
            'parent_id' => null,
            'text' => 'Begin and End of the Project',
            'content_type_id' => 3,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: Auto-Import from IVMC database',
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 18:58:02',
        ]);

        Question::create([
            'id' => 106,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '6',
            'order' => 6,
            'parent_id' => null,
            'text' => 'Project Stage',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => '',
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 107,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '7',
            'order' => 7,
            'parent_id' => null,
            'text' => 'Principal Investigator',
            'content_type_id' => 4,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: Auto-Import from IVMC database',
            'reference' => null,
            'guidance' => 'Please use the form "First Name Last Name". Please comma-separate your entries.',
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 109,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '8',
            'order' => 9,
            'parent_id' => null,
            'text' => 'Other Principal Investigators',
            'content_type_id' => 4,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: Auto-Import from IVMC database',
            'reference' => null,
            'guidance' => 'Please use the form "First Name Last Name". Please comma-separate your entries.',
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 111,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '9',
            'order' => 11,
            'parent_id' => null,
            'text' => 'External Project Partner',
            'content_type_id' => 5,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: Auto-Import from IVMC database',
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 112,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '10',
            'order' => 12,
            'parent_id' => null,
            'text' => 'Funding Source',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: Auto-Import from IVMC database',
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 113,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '11',
            'order' => 13,
            'parent_id' => null,
            'text' => 'Funding Program',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: Auto-Import from IVMC database',
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 114,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '12',
            'order' => 14,
            'parent_id' => null,
            'text' => 'Grant Reference Number',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 115,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '13',
            'order' => 15,
            'parent_id' => null,
            'text' => 'Project Management Organisation',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: Auto-Import from IVMC database',
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 116,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '14',
            'order' => 16,
            'parent_id' => null,
            'text' => 'Project Data Contact',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 117,
            'template_id' => 1,
            'section_id' => 1,
            'keynumber' => '15',
            'order' => 17,
            'parent_id' => null,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 0,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 121,
            'template_id' => 1,
            'section_id' => 2,
            'keynumber' => 'a)',
            'order' => 1,
            'parent_id' => null,
            'text' => 'Are there any existing procedures that you will base your approach on?',
            'content_type_id' => 2,
            'value' => 'In 2014, the Technische Universität Berlin (TU Berlin) established a research data infrastructure. It was developed by the Service Center Research Data and Publications (SZF]); a virtual organization, where the University Library, the IT-Service-Center tubIT and the Research Department of TU Berlin cooperate to support the researchers of TU Berlin in all questions concerning their research data (https://www.szf.tu-berlin.de/). The research data infrastructure complies with the requirements of the funding organizations, e.g. the Deutsche Forschungsgemeinschaft (DFG).

The technical core of the research data infrastructure at TU Berlin is the institutional repository DepositOnce. Another service developed by SZF is TUB-DMP, a web-tool to create data management plans. The IT services of SZF are integrated in the IT infrastructure of TU Berlin that is run by tubIT.

SZF developed a sustainable strategic concept to store the research data: In DepositOnce, researchers shall store their research results, i.e. consolidated research data and all information necessary to verify or reuse the data (e.g. scripts, calculations, software etc.)',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: DepositOnce Standard Value',
            'reference' => null,
            'guidance' => null,
            'hint' => '<ul>
<li>Kuberek, M. (2012): <a href="http://www.szf.tu-berlin.de/fileadmin/f33_szf/TUB_Forschungsdaten_Konzept_lang_20120315.pdf" target="_blank">Organisatorisch-technisches Konzept für eine Forschungsdaten-Infrastruktur in der TU Berlin</a></li>
<li><a href="http://www.szf.tu-berlin.de/" target="_blank">Website of SZF</a></li>
<li><a href="https://depositonce.tu-berlin.de" target="_blank">DepositOnce</a></li> 
</ul>
',
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 17:20:19',
        ]);

        Question::create([
            'id' => 122,
            'template_id' => 1,
            'section_id' => 2,
            'keynumber' => 'b)',
            'order' => 2,
            'parent_id' => null,
            'text' => 'Does your department/group have data management guidelines?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 123,
            'template_id' => 1,
            'section_id' => 2,
            'keynumber' => 'c)',
            'order' => 3,
            'parent_id' => null,
            'text' => 'Does your institution have a data protection or security policy that you will follow?',
            'content_type_id' => 2,
            'value' => 'Every new IT service at TU Berlin has to go through an approval procedure that is conducted by the Data Protection Officer of TU Berlin and the Staff Council. DepositOnce and TUB-DMP have successfully passed this procedure.',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: DepositOnce Standard Value',
            'reference' => null,
            'guidance' => null,
            'hint' => '<ul>
<li>IT policies of TU Berlin ("IT-Richtlinien der TU Berlin", several PDFs) on the website of TU Berlin: <a href="http://www.tu-berlin.de/menue/ueber_die_tu_berlin/gesetze_richt_leitlinien/" target="_blank">Gesetze, Richtlinien, Leitlinien</a></li>
<li>Information on the website of the Data Protection Officer of TU Berlin: <a href="https://www.tu-berlin.de/asv/menue/datenschutz/datenschutz_regelungen/" target="_blank">Datenschutz Regelungen</a></li>
</ul>
',
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 17:23:25',
        ]);

        Question::create([
            'id' => 124,
            'template_id' => 1,
            'section_id' => 2,
            'keynumber' => 'd)',
            'order' => 4,
            'parent_id' => null,
            'text' => 'Does your institution have a Research Data Management (RDM) policy?',
            'content_type_id' => 2,
            'value' => 'TU Berlin doesn’t have a RDM policy. However, since 2002 TU Berlin has a directive for safeguarding good scientific practice: "Richtlinien zur Sicherung guter wissenschaftlicher Praxis an der TU Berlin".',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: DepositOnce Standard Value',
            'reference' => null,
            'guidance' => null,
            'hint' => '<ul>
<li><a href="http://www.tu-berlin.de/menue/ueber_die_tu_berlin/gesetze_richt_leitlinien/richtlinien_zur_sicherung_guter_wissenschaftlicher_praxis/" target="_blank">Richtlinien zur Sicherung guter wissenschaftlicher Praxis an der TU Berlin</a></li>
</ul>',
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 21:08:04',
        ]);

        Question::create([
            'id' => 125,
            'template_id' => 1,
            'section_id' => 2,
            'keynumber' => 'e)',
            'order' => 5,
            'parent_id' => null,
            'text' => 'Does your funder have a Research Data Management (RDM) policy?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 126,
            'template_id' => 1,
            'section_id' => 2,
            'keynumber' => 'f)',
            'order' => 6,
            'parent_id' => null,
            'text' => 'Are there any formal standards that you will adopt?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 128,
            'template_id' => 1,
            'section_id' => 2,
            'keynumber' => 'g)',
            'order' => 8,
            'parent_id' => null,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 129,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => '1',
            'order' => 1,
            'parent_id' => null,
            'text' => 'What data will you collect or create?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Give a brief description of the data, including any existing data or third-party sources that will be used, in each case noting its content, type and coverage. Outline and justify your choice of format and consider the implications of data format and data volumes in terms of storage, backup and access.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 130,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => 'a)',
            'order' => 2,
            'parent_id' => 129,
            'text' => 'Type of data?',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'e.g. video data',
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 131,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => '',
            'order' => 2,
            'parent_id' => 130,
            'text' => 'If other:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 132,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => 'b)',
            'order' => 3,
            'parent_id' => 129,
            'text' => 'Format of the data?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 133,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => 'c)',
            'order' => 4,
            'parent_id' => 129,
            'text' => 'Volume of the data?',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 134,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => 'd)',
            'order' => 5,
            'parent_id' => 129,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 135,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => '2',
            'order' => 6,
            'parent_id' => null,
            'text' => 'How will the data be collected or created?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Outline how the data will be collected/created and which community data standards (if any) will be used. Consider how the data will be organized during the project, mentioning for example naming conventions, version control and folder structures. Explain how the consistency and quality of data collection will be controlled and documented. This may include processes such as calibration, repeat samples or measurements, standardized data capture or recording, data entry validation, peer reviews of data or representation with controlled vocabularies.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 136,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => 'a)',
            'order' => 7,
            'parent_id' => 135,
            'text' => 'What standards or methodologies will you use?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 137,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => 'b)',
            'order' => 8,
            'parent_id' => 135,
            'text' => 'How will you structure and name your folders and files?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 138,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => 'c)',
            'order' => 9,
            'parent_id' => 135,
            'text' => 'How will you handle versioning during the research?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 139,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => 'd)',
            'order' => 10,
            'parent_id' => 135,
            'text' => 'What quality assurance processes will you adopt?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 140,
            'template_id' => 1,
            'section_id' => 3,
            'keynumber' => 'e)',
            'order' => 11,
            'parent_id' => 135,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 141,
            'template_id' => 1,
            'section_id' => 4,
            'keynumber' => '1',
            'order' => 1,
            'parent_id' => null,
            'text' => 'What documentation and metadata will accompany the data?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Describe the types of documentation that will accompany the data to help secondary users to understand and reuse it. This should at least include basic details that will help people to find the data, including who created or contributed to the data, its title, date of creation and under what conditions it can be accessed.<br/>Documentation may also include details on the methodology used, analytical and procedural information, definitions of variables, vocabularies, units of measurement, any assumptions made, and the format and file type of the data. Consider how you will capture this information and where it will be recorded. Wherever possible you should identify and use existing community standards.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 142,
            'template_id' => 1,
            'section_id' => 4,
            'keynumber' => 'a)',
            'order' => 2,
            'parent_id' => 141,
            'text' => 'What information is needed for the data to be read and interpreted in the future?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 143,
            'template_id' => 1,
            'section_id' => 4,
            'keynumber' => 'b)',
            'order' => 3,
            'parent_id' => 141,
            'text' => 'How will you capture / create this documentation and metadata?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'If there is a separate publication about the data please provide information in the field below ("Further notes")',
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 144,
            'template_id' => 1,
            'section_id' => 4,
            'keynumber' => 'c)',
            'order' => 4,
            'parent_id' => 141,
            'text' => 'What metadata standards will you use and why?',
            'content_type_id' => 2,
            'value' => 'DepositOnce uses the standard metadata schema Qualified Dublin Core to describe the stored data. To meet the requirements of its service partners, e.g. the DOI registation agency DataCite or Open Access initiatives like OpenAIRE, the SZF-Team has added some additional qualifiers. Based on the principle of using standard metadata schemas in DepositOnce, metadata can easily be converted into other metadata schemas.',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: DepositOnce Standard Value',
            'reference' => null,
            'guidance' => null,
            'hint' => '<ul>
            <li>If required, other metadata schemas can be implemented in the future. In this case, please contact the <a href="mailto:team@szf.tu-berlin.de">SZF Team</a></li> 
            <li><a href="http://dublincore.org/documents/2000/07/11/dcmes-qualifiers/" target="_blank">Dublin Core</a></li>
            <li><a href="https://www.datacite.org/" target="_blank">DataCite</a></li> 
            <li><a href="https://www.openaire.eu/" target="_blank">OpenAIRE</a></li> 
            </ul>',
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 17:38:23',
        ]);

        Question::create([
            'id' => 145,
            'template_id' => 1,
            'section_id' => 4,
            'keynumber' => 'd)',
            'order' => 5,
            'parent_id' => 141,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 146,
            'template_id' => 1,
            'section_id' => 5,
            'keynumber' => '1',
            'order' => 1,
            'parent_id' => null,
            'text' => 'How will you manage ethical issues?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Ethical issues affect how you store data, who can see/use it and how long it is kept. Managing ethical concerns may include: anonymization of data, referral to departmental or institutional ethics committees; and formal consent agreements. You should show that you are aware of any issues and have planned accordingly. If you are carrying out research involving human participants, you must also ensure that consent is requested to allow data to be shared and reused.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 147,
            'template_id' => 1,
            'section_id' => 5,
            'keynumber' => 'a)',
            'order' => 2,
            'parent_id' => 146,
            'text' => 'How will you protect the identity of participants if required?',
            'content_type_id' => 2,
            'value' => 'All contents that are stored in DepositOnce have to be anonymized according to the policy for safeguarding good scientific practice of TU Berlin.
            
When submitting a data file in DepositOnce the submitter has to confirm that the research data which he submitted do not contain any personal data. If personal data are contained they must be anonymized completely according to canonical standards and the human subjects must have consented to the data collection as well as to the publication of the (anonymized) data."
',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => '<ul>
<li>DepositOnce meets the requirements of the data protection officer of TU Berlin regarding the anonymization. The question of anonymization was part of the approval procedure which DepositOnce has passed successfully.</li> 
</ul>',
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-19 10:57:54',
        ]);

        Question::create([
            'id' => 148,
            'template_id' => 1,
            'section_id' => 5,
            'keynumber' => 'b)',
            'order' => 3,
            'parent_id' => 146,
            'text' => 'Method(s) of anonymization?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 149,
            'template_id' => 1,
            'section_id' => 5,
            'keynumber' => 'c)',
            'order' => 4,
            'parent_id' => 146,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 150,
            'template_id' => 1,
            'section_id' => 5,
            'keynumber' => '2',
            'order' => 3,
            'parent_id' => null,
            'text' => 'How will you manage copyright issues and Intellectual Property Rights (IPR) issues?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'State who will own the copyright and IPR of any data that you will collect or create, along with the licence(s) for its use and reuse. For multi-partner projects, IPR ownership may be worth covering in a consortium agreement. Consider any relevant funder, institutional, departmental or group policies on copyright or IPR. Also consider permissions to reuse third-party data and any restrictions needed on data sharing.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 151,
            'template_id' => 1,
            'section_id' => 5,
            'keynumber' => 'a)',
            'order' => 4,
            'parent_id' => 150,
            'text' => 'Who owns the data?',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 152,
            'template_id' => 1,
            'section_id' => 5,
            'keynumber' => 'b)',
            'order' => 5,
            'parent_id' => 150,
            'text' => 'How will the data be licensed for reuse?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Licenses such as CC, GPL, ...',
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 153,
            'template_id' => 1,
            'section_id' => 5,
            'keynumber' => 'c)',
            'order' => 7,
            'parent_id' => 150,
            'text' => 'Are there any restrictions on the reuse of 3rd party data?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 155,
            'template_id' => 1,
            'section_id' => 5,
            'keynumber' => 'd)',
            'order' => 9,
            'parent_id' => 150,
            'text' => 'Will data sharing be postponed / restricted, e.g. to publish and seek patents?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 157,
            'template_id' => 1,
            'section_id' => 5,
            'keynumber' => 'e)',
            'order' => 11,
            'parent_id' => 150,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 158,
            'template_id' => 1,
            'section_id' => 6,
            'keynumber' => '1',
            'order' => 1,
            'parent_id' => null,
            'text' => 'How will the data be stored and backed up during the research?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'State how often the data will be backed up and to which locations. How many copies are being made? Storing data on laptops, computer hard drives or external storage devices alone is very risky. The use of robust, managed storage provided by university IT teams is preferable. Similarly, it is normally better to use automatic backup services provided by IT Services than rely on manual processes. If you choose to use a third-party service, you should ensure that this does not conflict with any funder, institutional, departmental or group policies, for example in terms of the legal jurisdiction in which data are held or the protection of sensitive data.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 18:03:06',
        ]);

        Question::create([
            'id' => 159,
            'template_id' => 1,
            'section_id' => 6,
            'keynumber' => 'a)',
            'order' => 2,
            'parent_id' => 158,
            'text' => 'How will the data be backed up?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 160,
            'template_id' => 1,
            'section_id' => 6,
            'keynumber' => 'b)',
            'order' => 3,
            'parent_id' => 158,
            'text' => 'Who will be responsible for backup and recovery?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 161,
            'template_id' => 1,
            'section_id' => 6,
            'keynumber' => 'c)',
            'order' => 4,
            'parent_id' => 158,
            'text' => 'How will the data be recovered in the event of an incident?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 162,
            'template_id' => 1,
            'section_id' => 6,
            'keynumber' => 'd)',
            'order' => 5,
            'parent_id' => 158,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 163,
            'template_id' => 1,
            'section_id' => 6,
            'keynumber' => '2',
            'order' => 6,
            'parent_id' => null,
            'text' => 'How will you manage access and security during the research?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'If your data is confidential (e.g. personal data not already in the public domain, confidential information or trade secrets]); you should outline any appropriate security measures and note any formal standards that you will comply with e.g. ISO 27001.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 18:04:35',
        ]);

        Question::create([
            'id' => 164,
            'template_id' => 1,
            'section_id' => 6,
            'keynumber' => 'a)',
            'order' => 7,
            'parent_id' => 163,
            'text' => 'If creating or collection data in the field how will you ensure its safe transfer into your main secured systems?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 165,
            'template_id' => 1,
            'section_id' => 6,
            'keynumber' => 'b)',
            'order' => 8,
            'parent_id' => 163,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 166,
            'template_id' => 1,
            'section_id' => 7,
            'keynumber' => '1',
            'order' => 1,
            'parent_id' => null,
            'text' => 'Which data should be retained, shared, and/or preserved?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Consider how the data may be reused e.g. to validate your research findings, conduct new studies, or for teaching. Decide which data to keep and for how long. This could be based on any obligations to retain certain data, the potential reuse value, what is economically viable to keep, and any additional effort required to prepare the data for data sharing and preservation. Remember to consider any additional effort required to prepare the data for sharing and preservation, such as changing file formats.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 167,
            'template_id' => 1,
            'section_id' => 7,
            'keynumber' => 'a)',
            'order' => 2,
            'parent_id' => 166,
            'text' => 'What data must be retained / destroyed for contractual, legal, or regulatory purposes?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 168,
            'template_id' => 1,
            'section_id' => 7,
            'keynumber' => 'b)',
            'order' => 3,
            'parent_id' => 166,
            'text' => 'What are the foreseeable research uses for the data?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 169,
            'template_id' => 1,
            'section_id' => 6,
            'keynumber' => 'c)',
            'order' => 4,
            'parent_id' => 166,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 170,
            'template_id' => 1,
            'section_id' => 7,
            'keynumber' => '2',
            'order' => 5,
            'parent_id' => null,
            'text' => 'What is the long term preservation plan for the dataset?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Consider how datasets that have long-term value will be preserved and curated beyond the lifetime of the grant. Also outline the plans for preparing and documenting data for sharing and archiving. If you do not propose to use an established repository, the data management plan should demonstrate that resources and systems will be in place to enable the data to be curated effectively beyond the lifetime of the grant.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 14:06:41',
        ]);

        Question::create([
            'id' => 171,
            'template_id' => 1,
            'section_id' => 7,
            'keynumber' => 'a)',
            'order' => 6,
            'parent_id' => 170,
            'text' => 'Information about your selected repository',
            'content_type_id' => 2,
            'value' => 'The repository DepositOnce is operated by the Service Center for Research Data and Publications (SZF) of TU Berlin, a virtual organization consisting of the University Library, the IT Service Center tubIT and the Research Department. It is based on the open source repository software DSpace. In DepositOnce research data as well as publications of all kind of disciplines and all kind of formats can be stored.
            
DepositOnce provides a workflow for the description and upload of the data files. There is a record for each data set (research data as well as publications). Each record has a persistent identifier (DOI). Research data may be linked to the corresponding publications and vice versa via their DOIs. Other core functions of DepositOnce are the versioning and an embargo function (i.e. a blocking period for the publication of full texts and research data until a certain date).
            
Operational concept of DepositOnce:
DepositOnce uses the virtual server infrastructure of tubIT. All servers, networks and backup services are maintained by tubIT. The metadata as well as the research data are backed-up at least once a day in form of database dumps and files. A cronjob verifies file checksums once a week and ensures the data integrity.
            
Security concept of DepositOnce:
The DepositOnce servers that store the research data and their metadata are part of the security concept of tubIT. They are located within the DMZ of tubIT and are secured by several firewalls. The security concept strictly restricts any physical access to the data center and any remote access to the servers.
            
Responsibilities for DepositOnce:
- tubIT is responsible for the servers, network and backup services.
- The administrators at the University Library are responsible for the further enhancement and development of the software. They are also responsible for the recovery of the DepositOnce services out of the backup.
            
Terms of use:
- The guidelines for DepositOnce "Leitlinien für DepositOnce" are published on the SZF website.',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: DepositOnce Standard Value',
            'reference' => null,
            'guidance' => 'e.g. provider, operational concept, responsibilities for data storage/backup, terms of use, etc.',
            'hint' => '<ul>
<li>Terms of Use: "<a href="http://www.szf.tu-berlin.de/menue/dienste_tools/repositorium_depositonce/leitlinien_fuer_depositonce/" target="_blank">Leitlinien für DepositOnce</a>"</li>
</ul>',
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:41',
            'updated_at' => '2016-04-15 18:28:19',
        ]);

        Question::create([
            'id' => 172,
            'template_id' => 1,
            'section_id' => 7,
            'keynumber' => 'b)',
            'order' => 7,
            'parent_id' => 170,
            'text' => 'How long will the data be retained and preserved?',
            'content_type_id' => 2,
            'value' => 'According to the policy for safeguarding good scientific practice of TU Berlin, SZF as the service provider of DepositOnce guarantees the storage of the research data for at least 10 years.
In cooperation with other partners and institutions (e.g. the Zuse Institute Berlin and the Kooperativer Bibliotheksverbund Berlin-Brandenburg]); SZF will develop a concept for long term preservation.',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: DepositOnce Standard Value',
            'reference' => null,
            'guidance' => null,
            'hint' => '<ul>
<li><a href="http://www.zib.de/" target="_blank">Zuse Institute Berlin (ZIB)</a></li>
<li><a href="http://www.kobv.de/" target="_blank">Kooperativer Bibliotheksverbund Berlin-Brandenburg (KOBV)</a></li>
</ul>',
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 18:35:50',
        ]);

        Question::create([
            'id' => 173,
            'template_id' => 1,
            'section_id' => 7,
            'keynumber' => 'c)',
            'order' => 8,
            'parent_id' => 170,
            'text' => 'How will you handle versioning in the long-term?',
            'content_type_id' => 2,
            'value' => 'According to the principle of "Good Scientific Practice" (e.g. on order to guarantee correct citation) the data file and the descriptive metadata cannot be changed after they have been published in DepositOnce. One of the core functions of DepositOnce is versioning, which allows new versions of published records while previous versions are kept available. To every new version, a new persistent identifier (DOI) is assigned. Previous and new versions are linked to each other automatically.',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: DepositOnce Standard Value',
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-19 10:59:09',
        ]);

        Question::create([
            'id' => 174,
            'template_id' => 1,
            'section_id' => 7,
            'keynumber' => 'd)',
            'order' => 9,
            'parent_id' => 170,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 175,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => '1',
            'order' => 1,
            'parent_id' => null,
            'text' => 'How will you share the data?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Consider where, how, and to whom data with acknowledged long-term value should be made available. The methods used to share data will be dependent on a number of factors such as the type, size, complexity and sensitivity of data. If possible, mention earlier examples to show a track record of effective data sharing. Consider how people might acknowledge the reuse of your data.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 176,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => 'a)',
            'order' => 2,
            'parent_id' => 175,
            'text' => 'How will potential users find out about your data?',
            'content_type_id' => 2,
            'value' => 'All metadata in DepositOnce are made publicly available in the sense of Open Access. To enable search engines and service providers to index contents stored in DepositOnce, SZF takes all reasonable steps: like generating sitemaps, offering an OAI-PMH interface etc. DepositOnce is included in common search engines, e.g. Google Scholar,  BASE – Bielefeld Academic Search Engine and others. Furthermore the DOI registration agency DataCite itself acts as a data provider: While registering a DOI all important metadata are sent to DataCite.',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: DepositOnce Standard Value',
            'reference' => null,
            'guidance' => null,
            'hint' => '<ul>
            <li><a href="https://www.base-search.net/" target="_blank">BASE – Bielefeld Academic Search Engine</a></li>
            </ul>',
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 18:36:30',
        ]);

        Question::create([
            'id' => 177,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => 'b)',
            'order' => 3,
            'parent_id' => 175,
            'text' => 'With whom will you share the data, and under what conditions?',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 178,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => 'c)',
            'order' => 4,
            'parent_id' => 175,
            'text' => 'When will you make the data available?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 179,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => 'd)',
            'order' => 5,
            'parent_id' => 175,
            'text' => 'Will you have a persistent identifier for your data?',
            'content_type_id' => 2,
            'value' => 'DepositOnce automatically assigns a DOI (Digital Object Identifier) to every submitted record and each of its versions. To get DOIs, the University Library (as head of SZF) has concluded a contract with the DOI registration agency DataCite.',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => 'Source: DepositOnce Standard Value',
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 180,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => 'e)',
            'order' => 6,
            'parent_id' => 175,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 181,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => '2',
            'order' => 7,
            'parent_id' => null,
            'text' => 'Are any restrictions on data sharing required?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Outline any expected difficulties in sharing data with acknowledged long-term value, along with causes and possible measures to overcome these. Restrictions may be due to confidentiality, lack of consent agreements or IPR, for example. Consider whether a non-disclosure agreement would give sufficient protection for confidential data.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 182,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => 'a)',
            'order' => 8,
            'parent_id' => 181,
            'text' => 'What action will you take to overcome or minimize restrictions?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 183,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => 'b)',
            'order' => 9,
            'parent_id' => 181,
            'text' => 'For how long do you need exclusive use of the data and why?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 184,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => 'c)',
            'order' => 10,
            'parent_id' => 181,
            'text' => 'Will a sharing agreement (or equivalent) be required?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 186,
            'template_id' => 1,
            'section_id' => 8,
            'keynumber' => 'd)',
            'order' => 12,
            'parent_id' => 181,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 187,
            'template_id' => 1,
            'section_id' => 9,
            'keynumber' => '1',
            'order' => 1,
            'parent_id' => null,
            'text' => 'Who will be responsible for data management?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Outline the roles and responsibilities for all activities e.g. data capture, metadata production, data quality, storage and backup, data archiving & data sharing. Consider who will be responsible for ensuring relevant policies will be respected. Individuals should be named where possible.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 188,
            'template_id' => 1,
            'section_id' => 9,
            'keynumber' => 'a)',
            'order' => 2,
            'parent_id' => 187,
            'text' => 'Who is responsible for ensuring that the data management plan is reviewed and revised?',
            'content_type_id' => 1,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 189,
            'template_id' => 1,
            'section_id' => 9,
            'keynumber' => 'b)',
            'order' => 3,
            'parent_id' => 187,
            'text' => 'Who will be responsible for each data management activity?',
            'content_type_id' => 2,
            'value' => 'According to the concept of the research data infrastructure the task-sharing between the stakeholders is as following:
            
- The researchers are responsible for the quality check of the research results: After having collected a large amount of data during the project they select those data that shall be preserved. In the submission process to DepositOnce they describe these data and upload the data files. Researchers are also responsible to create new versions of published submissions if necessary. The submission process of a new version is the same as the primary process.
            
- The SZF-Team is responsible for the formal check of the submitted research data: The uploaded data files are not published immediately but stored in an intermediate store. The SZF-Team checks e.g. whether the metadata fields are filled properly, whether PDFs can be opened, etc. If there are any questions, the SZF-Team contacts the submitter of the data. Accepted submissions are published by the SZF- Team and stored in DepositOnce.
            
- tubIT is responsible for the IT infrastructure which includes the safe storage and the accessibility of all data.',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => '<ul>
<li>See also: Research Data Lifecycle - Responsibilities and Workflows "<a href="http://www.szf.tu-berlin.de/menue/ueber_das_szf/forschungsdaten_lifecycle/" target="_blank">Forschungsdaten-Lifecycle - Zuständigkeiten und Workflows</a>"</li>
</ul>',
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-19 11:06:44',
        ]);

        Question::create([
            'id' => 190,
            'template_id' => 1,
            'section_id' => 9,
            'keynumber' => 'c)',
            'order' => 4,
            'parent_id' => 187,
            'text' => 'How will responsibilities be split across partner sites in collaborative research projects?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 191,
            'template_id' => 1,
            'section_id' => 9,
            'keynumber' => 'd)',
            'order' => 5,
            'parent_id' => 187,
            'text' => 'Will data ownership and responsibilities for research data management (RDM) be part of any consortium agreement or contract agreed between partners?',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 193,
            'template_id' => 1,
            'section_id' => 9,
            'keynumber' => 'e)',
            'order' => 7,
            'parent_id' => 187,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);

        Question::create([
            'id' => 194,
            'template_id' => 1,
            'section_id' => 9,
            'keynumber' => '2',
            'order' => 8,
            'parent_id' => null,
            'text' => 'What resources will you require to deliver your data management plan?',
            'content_type_id' => 99,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => 'Carefully consider any resources needed to deliver the plan, e.g. software, hardware, technical expertise, etc. Where dedicated resources are needed, these should be outlined and justified.',
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 18:42:06',
        ]);

        Question::create([
            'id' => 195,
            'template_id' => 1,
            'section_id' => 9,
            'keynumber' => 'a)',
            'order' => 9,
            'parent_id' => 194,
            'text' => 'Do you require hardware or software for your data management plan tool which is additional or exceptional to existing institutional provision?',
            'content_type_id' => 2,
            'value' => 'The data management plan tool TUB-DMP is a service of SZF and is maintained by the University Library. For the web tool TUB-DMP no additional hardware or software is required.',
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 1,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 18:44:26',
        ]);

        Question::create([
            'id' => 196,
            'template_id' => 1,
            'section_id' => 9,
            'keynumber' => 'b)',
            'order' => 10,
            'parent_id' => 194,
            'text' => 'Further notes:',
            'content_type_id' => 2,
            'value' => null,
            'default' => null,
            'prepend' => null,
            'append' => null,
            'comment' => null,
            'reference' => null,
            'guidance' => null,
            'hint' => null,
            'is_mandatory' => 0,
            'is_active' => 1,
            'read_only' => 0,
            'created_at' => '2016-04-15 14:06:42',
            'updated_at' => '2016-04-15 14:06:42',
        ]);
    }
}